### PR TITLE
Radius Calc and Units Fix

### PR DESCRIPTION
**Pull request by pmskintner**
- Fixed L_TO_GAL in getTankVolume()
- Fixed Issue where heat lost from top and bottom wasn't added to standby
- DRYed newer getters and setters so defualt args take units.
- Added SA and length UNITS
- Add calculation for tank radius in for use in UA losses
- Updated ref tests
- getTankSurfaceArea takes UNITS_FT2 or UNITS_M2

### CODE REVIEW

**Review by chipbarnaby — APPROVED** [review]
The DRYing could be much simpler with default arguments ...

in HPWH.hh --
getXXX( UNITS units=UNITS_L)  or whatever

Then no need to change existing no-arg calls.

In other words, get default and non-default behavior out of one variant of the function.

**Comment by chipbarnaby** [comment]
I approved but note my comment.  Did not merge.

**Comment by pmskintner** [comment]
That makes perfect sense Chip. I'll change them up right now.

**Comment by pmskintner** [comment]
Hey Chip, do you want to review changes again?

**Review by chipbarnaby — APPROVED** [review]
Looks good.
I often show default arg value in a comment in the implementation file --

float getXXX( UNITS units /*=UNITS_FURLONGS*/)
{    return blah blah
}

**Comment by pmskintner** [comment]
Slowly but surely I'll perfect HPWHsim. I'll add this in so it's clear and merge this.

**Pull request merged**
